name: Deploy to Dev Org

on:
  pull_request:
    branches:
      - master

jobs:
  validate_and_deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL_DEV }}" > authfile.txt
          sf org login sfdx-url --sfdx-url-file authfile.txt --alias dev-org

      - name: Run Apex Tests
        run: |
          sf apex run test --target-org dev-org --wait 10 --code-coverage

      - name: Deploy to Dev Org
        run: |
          sf project deploy start \
          --source-dir force-app \
          --target-org dev-org \
          --test-level RunLocalTests